
- name: "Installing basic software"
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - dnsutils
      - git
      - ntp
      - vim
      - curl
      - vim-athena

- name: Copy .vimrc
  copy: 
    src: ../files/.vimrc
    dest: ~/
    owner: admin
    group: admin
    mode: 0600

- name: VIM VundleVIM Install
  command: vim +PluginInstall +qall
