---

- hosts: all
  remote_user: admin
  roles:
    - set_apt_proxy
    - update
    - basic_software
    - role: gantsign.oh-my-zsh
      users: 
        - username: admin
    - browsers
    - basic_tools
    - unset_apt_proxy
    - role: lean_delivery.mysql
      become: yes
    - dev_software
    - vmware.vmware-workstation
    - ide
    - powerlevel10k
  vars:
    mysql_root_password: root
    mysql_port: 3306
    mysql_bind_address: '0.0.0.0'
    mysql_daemon: mysqld
    mysql_version: 5.7
    workstation_license: XXX-YYY-XXX
