- name: cache
  become: true
  apt:
    update_cache: yes
- name: os (dist)
  become: true
  apt:
    upgrade: dist
- name: all packages
  become: true
  apt:
    name: "*"
    state: latest
- name: python3
  become: true
  apt: 
    name: python3

