- name: Upload fonts
  become: yes
  copy: 
    src: "{{ item }}"
    dest: /usr/share/fonts
  with_items:
    - MesloLGS_NF_Bold_Italic.ttf
    - MesloLGS_NF_Bold.ttf
    - MesloLGS_NF_Italic.ttf
    - MesloLGS_NF_Regular.ttf

- name: Create powerlevel10k folder
  become: yes
  file: 
    path: /opt/powerlevel10k
    state: directory

- name: Clone powerlevel10k
  become: yes
  git:
     repo: https://github.com/romkatv/powerlevel10k.git
     dest: /opt/powerlevel10k

- name: Set oh-my-shell theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="powerlevel10k/powerlevel10k"

- name: Set powerlevel9k mode 
  lineinfile:
    path: ~/.zshrc
    insertafter: '^ZSH_THEME='
    line: POWERLEVEL9K_MODE="awesome-patched"

- name: Upload .p10k.zsh
  copy:
    src: .p10k.zsh
    dest: ~/.p10k.zsh

- name: Add p10k configuration to zshrc
  lineinfile:
    path: ~/.zshrc
    line: " [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
