- name: Upload fonts
  become: yes
  copy: 
    src: "{{ item }}"
    dest: /usr/share/fonts
  with_items:
    - MesloLGS_NF_Bold_Italic.ttf
    - MesloLGS_NF_Bold.ttf
    - MesloLGS_NF_Italic.ttf
    - MesloLGS_NF_Regular.ttf
