- name: "Install nginx"
  become: yes
  apt:
    name: nginx

- name: Configure nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ http_conf }}"

- name: Enable new site
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ http_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
    state: link
  notify:  restart-nginx

- name: Remove default site
  become: yes
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart-nginx

