- name: Installing PHP
  become: yes
  apt:
    name: "{{ packages }}"
  vars: 
    packages:
      - php-fpm
      - php-mysql

- name: Upload PHP Info Page
  become: yes
  template:
    src: ../files/info.php
    dest: /var/www/html/info.php

- name: Check composer
  command: composer -v 
  register: composer_v_result
  ignore_errors: yes

- name: Download Composer
  become: yes
  script: ../scripts/install_composer.zsh
  when: composer_v_result is failed

- name: Move Composer Globally
  become: yes
  command: mv composer.phar /usr/local/bin/composer
  when: composer_v_result is failed

- name: Set Composer exection permissions
  become: yes
  file:
    path: /usr/local/bin/composer
    mode: "a+x"
